apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  namespace: netflix
  labels:
    app: netflix-app
spec:
  type: LoadBalancer
  ports:
    - port: 80        # Service port
      targetPort: 80 # Container port
  selector:
    app: netflix-app
